public sealed record PostingResponse(
    int Id,
    string EmployerWallet,
    string? EmployerDisplayName,
    string Title,
    string? Summary,
    string? Description,
    string Category,
    List<string> Skills,
    string JobType,
    string BudgetType,
    decimal? BudgetMin,
    decimal? BudgetMax,
    string? Timeline,
    string ExperienceLevel,
    string Visibility,
    DateTime? ProposalDeadline,
    string Status,
    int ProposalCount,
    DateTime CreatedAt,
    DateTime? PublishedAt,
    bool HasBriefAttachment,
    List<string> ScreeningQuestions
);
